<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { deleteEntry, diaryState, persist } from '../stores/diary';import { compressImage,imageRepository } from '../lib/image-repository'
const route=useRoute(),router=useRouter(),entry=computed(()=>diaryState.entries.find(e=>e.id===route.params.id));const body=ref(''),tomorrow=ref(''),photos=ref<{id:string,url:string,blob:Blob}[]>([]),lightbox=ref(''),error=ref('');const originalIds=ref<string[]>([])
onMounted(async()=>{if(!entry.value)return;body.value=entry.value.body;tomorrow.value=entry.value.tomorrow;originalIds.value=[...entry.value.imageIds];for(const id of entry.value.imageIds){const im=await imageRepository.get(id);if(im)photos.value.push({id,url:URL.createObjectURL(im.blob),blob:im.blob})}});onBeforeUnmount(()=>photos.value.forEach(p=>URL.revokeObjectURL(p.url)))
async function addFiles(ev:Event){const files=[...(ev.target as HTMLInputElement).files||[]];if(photos.value.length+files.length>5){error.value='写真は5枚まで追加できます。';return}for(const f of files){try{const blob=await compressImage(f),id=crypto.randomUUID();photos.value.push({id,url:URL.createObjectURL(blob),blob})}catch{error.value='写真を読み込めませんでした。'}}}
function remove(id:string){if(!confirm('この写真を日記から削除しますか？'))return;photos.value=photos.value.filter(p=>p.id!==id);if(entry.value?.thumbnailImageId===id)entry.value.thumbnailImageId=photos.value[0]?.id}
async function save(){if(!entry.value)return;entry.value.body=body.value;entry.value.tomorrow=tomorrow.value;entry.value.imageIds=photos.value.map(p=>p.id);entry.value.updatedAt=new Date().toISOString();await Promise.all(photos.value.filter(p=>!originalIds.value.includes(p.id)).map(p=>imageRepository.put({id:p.id,entryId:entry.value!.id,blob:p.blob,type:p.blob.type,createdAt:new Date().toISOString()})));await Promise.all(originalIds.value.filter(id=>!entry.value!.imageIds.includes(id)).map(imageRepository.delete));persist();router.push('/records')}
async function removeEntry(){if(entry.value&&confirm('この日の記録を削除しますか？')){await deleteEntry(entry.value.id);router.push('/records')}}
</script>
<template><div v-if="entry" class="page detail-page"><header class="detail-nav"><button @click="router.back()">‹</button><button class="danger" @click="removeEntry">削除</button></header><p class="eyebrow">{{new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(entry.date+'T12:00'))}}</p><h1>{{entry.guess}}</h1><div class="tag-list"><span v-for="t in entry.tags"># {{t}}</span></div><div v-if="photos.length" class="detail-gallery"><div v-for="p in photos" :key="p.id" class="gallery-image" :class="{selected:entry.thumbnailImageId===p.id}"><img :src="p.url" alt="日記の写真" @click="lightbox=p.url"><button @click="remove(p.id)">×</button><button @click="entry.thumbnailImageId=p.id">{{entry.thumbnailImageId===p.id?'✓ 代表写真':'代表にする'}}</button></div></div><div class="photo-actions" v-if="photos.length<5"><label class="outline-button">＋ 写真を選ぶ<input type="file" accept="image/*" multiple @change="addFiles"></label><label class="outline-button">⌾ カメラ<input type="file" accept="image/*" capture="environment" @change="addFiles"></label></div><p class="error" v-if="error">{{error}}</p><label>今日のこと<textarea v-model="body"></textarea></label><label>明日やりたいこと<input v-model="tomorrow"></label><button class="primary-button full" @click="save">変更を保存する</button><div v-if="lightbox" class="lightbox" @click="lightbox=''"> <img :src="lightbox" alt="拡大した日記の写真"><button>×</button></div></div></template>
