<script setup lang="ts">
import { computed, ref } from 'vue';import { useRouter } from 'vue-router';import { baseQuestions, buildGuess, visibleActivityQuestions } from '../data/questions';import { compressImage, imageRepository } from '../lib/image-repository';import { saveEntry } from '../stores/diary';import type { DiaryEntry, DiaryImage, GuessResult, MoodValue, QuestionNode } from '../types'
const router=useRouter(),step=ref(0),answers=ref<Record<string,string>>({}),guess=ref<GuessResult>(),guessResult=ref<DiaryEntry['guessResult']>('correct'),body=ref(''),tomorrow=ref(''),stage=ref<'questions'|'guess'|'finish'|'done'>('questions'),images=ref<{id:string,url:string,blob:Blob}[]>([]),thumbnail=ref(''),error=ref('')
const questions=computed(()=>[...baseQuestions,...visibleActivityQuestions(answers.value)]);const current=computed<QuestionNode|undefined>(()=>questions.value[step.value]);const progress=computed(()=>Math.min(88,14+step.value*10))
function answer(v:string){if(!current.value)return;answers.value={...answers.value,[current.value.id]:v};if(step.value>=questions.value.length-1||step.value>=8){guess.value=buildGuess(answers.value);stage.value='guess'}else step.value++}
function back(){if(stage.value==='guess'){stage.value='questions'}else if(stage.value==='finish'){stage.value='guess'}else if(step.value>0){const key=questions.value[step.value-1]?.id;const next={...answers.value};delete next[key];answers.value=next;step.value--}else router.back()}
function confirmGuess(v:DiaryEntry['guessResult']){guessResult.value=v;stage.value='finish'}
async function addFiles(event:Event){error.value='';const files=[...(event.target as HTMLInputElement).files||[]];if(images.value.length+files.length>5){error.value='写真は5枚まで追加できます。';return}for(const f of files){if(!['image/jpeg','image/png','image/webp'].includes(f.type)){error.value='JPEG、PNG、WebPの写真を選んでください。';continue}try{const blob=await compressImage(f),id=crypto.randomUUID();images.value.push({id,blob,url:URL.createObjectURL(blob)});if(!thumbnail.value)thumbnail.value=id}catch{error.value='この写真は読み込めませんでした。'}}(event.target as HTMLInputElement).value=''}
function removeImage(id:string){if(!confirm('この写真を日記から外しますか？'))return;const i=images.value.find(x=>x.id===id);if(i)URL.revokeObjectURL(i.url);images.value=images.value.filter(x=>x.id!==id);if(thumbnail.value===id)thumbnail.value=images.value[0]?.id||''}
async function save(){const id=crypto.randomUUID(),now=new Date().toISOString();const entry:DiaryEntry={id,date:now.slice(0,10),mood:Number(answers.value.mood||3) as MoodValue,condition:Number(answers.value.condition||3),answers:answers.value,tags:guess.value?.tags||[],guess:guess.value?.text||'',guessResult:guessResult.value,body:body.value||guess.value?.text||'今日のことを、そっと残しました。',tomorrow:tomorrow.value,imageIds:images.value.map(x=>x.id),thumbnailImageId:thumbnail.value||undefined,createdAt:now,updatedAt:now};saveEntry(entry);try{await Promise.all(images.value.map(x=>imageRepository.put({id:x.id,entryId:id,blob:x.blob,type:x.blob.type,createdAt:now} satisfies DiaryImage)))}catch{error.value='日記は保存できましたが、一部の写真を保存できませんでした。'}stage.value='done'}
</script>
<template><div class="journal-page">
 <header class="journal-header"><button class="icon-button" @click="back" aria-label="戻る">‹</button><div class="progress"><i :style="{width:progress+'%'}"></i></div><button class="text-button" @click="stage==='questions'&&answer('skip')">スキップ</button></header>
 <Transition name="question" mode="out-in">
  <section v-if="stage==='questions'&&current" :key="current.id" class="question-pane"><div><p class="eyebrow">{{current.eyebrow||'今日を、もう少しだけ'}}</p><h1>{{current.prompt}}</h1><p class="question-help">考えすぎなくても大丈夫。近いものを選んでください。</p></div><div class="answer-grid" :class="{moods:current.id==='mood'}"><button v-for="o in current.options" :key="o.value" @click="answer(o.value)"><span v-if="o.icon">{{o.icon}}</span>{{o.label}}<b>›</b></button></div></section>
  <section v-else-if="stage==='guess'" key="guess" class="question-pane guess-pane"><div><p class="eyebrow">今日のことが見えてきました</p><h1>もしかして…</h1></div><div class="guess-card"><span>🍃</span><h2>「{{guess?.text}}」</h2><p>こんな一日でしたか？</p></div><div class="guess-actions"><button @click="confirmGuess('correct')">その通り</button><button @click="confirmGuess('close')">少し違う</button><button @click="confirmGuess('wrong')">違う</button></div></section>
  <section v-else-if="stage==='finish'" key="finish" class="finish-pane"><div><p class="eyebrow">最後に、あなたの言葉で</p><h1>今日を仕上げましょう</h1></div><label>今日のこと<textarea v-model="body" :placeholder="guessResult==='correct'?'ひとこと付け足してもいいですね':'実際は何をしましたか？'"></textarea></label><label>明日やりたいこと <small>任意</small><input v-model="tomorrow" placeholder="例：少し早く休む" /></label><div><div class="photo-heading"><label>今日の写真 <small>{{images.length}} / 5</small></label></div><div class="photo-strip"><div v-for="img in images" :key="img.id" class="photo-item" :class="{selected:thumbnail===img.id}"><img :src="img.url" alt="追加した写真"><button class="remove" @click="removeImage(img.id)">×</button><button class="cover" @click="thumbnail=img.id">{{thumbnail===img.id?'✓ 代表写真':'代表にする'}}</button></div><label v-if="images.length<5" class="add-photo">＋<span>写真を選ぶ</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple @change="addFiles"></label><label v-if="images.length<5" class="add-photo">⌾<span>カメラ</span><input type="file" accept="image/*" capture="environment" @change="addFiles"></label></div><p v-if="error" class="error">{{error}}</p></div><button class="primary-button full" @click="save">今日を保存する</button></section>
  <section v-else key="done" class="done-pane"><div class="sprout"><i></i><b>⌁</b></div><p class="eyebrow">SAVED FOR TODAY</p><h1>今日も残せました</h1><p>あなたの一日が、またひとつここに。<br>また書きたくなった日にどうぞ。</p><button class="primary-button" @click="router.push('/')">ホームへ戻る</button></section>
 </Transition>
</div></template>
